trigger:
- none

stages:
- stage: PS_Gallery_Deploy
  displayName: PS Gallery Deploy
  jobs:
  - job: Install_Dependencies
    displayName: Install dependencies
    pool:
      vmImage: windows-latest
    steps:
    - task: PowerShell@2
      displayName: Version Check
      inputs:
        targetType: inline
        pwsh: true
        script: |
          Write-Output $PSVersionTable

  - job: Release_Approval
    displayName: Agentless job
    pool: server
    timeoutInMinutes: 1440 # job times out in 1 days
    steps:
    - task: ManualValidation@1
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: ''
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'

  - job: PsGallery_Push
    displayName: Push to PS Gallery
    pool:
      vmImage: windows-latest
    timeoutInMinutes: 6120
    steps:
    - task: powershell@2
      inputs:
        targetType: inline
        script: |
          Publish-Module -NuGetApiKey $env:NuGetApiKey -Path $(Build.ArtifactStagingDirectory)/modules/Microsoft.Graph.Entra -Verbose
          Publish-Module -NuGetApiKey $env:NuGetApiKey -Path $(Build.ArtifactStagingDirectory)/modules/Microsoft.Graph.Entra.Beta -Verbose
        pwsh: false
    dependsOn: Release_Approval