# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - main
pr: none

# variables:
#   WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest'
parameters:
  - name: Pack
    type: boolean
    default: true
  - name: Sign
    type: boolean
    default: true
resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/heads/main

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    # featureFlags:
    #   WindowsHostVersion: 1ESWindows2022
    stages:
    - stage: build
      jobs:
      - job: EntraPowerShellCIBuild
        displayName: Entra PowerShell CI Build
        timeoutInMinutes: 840
        pool:
          os: windows
        # variables:
        #   ob_outputDirectory: '$(Build.SourcesDirectory)/out'
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: $(System.DefaultWorkingDirectory)/Samples
            artifactName: entraPS
        steps:
          - template: .azure-pipelines/common-templates/install-tools.yml@self
          - template: .azure-pipelines/common-templates/security-pre-checks.yml@self

          - template: .azure-pipelines/generation-templates/generate_adapter-migrate.yml@self
            parameters:
              Sign: ${{ parameters.Sign }}

          - ${{ if and(eq(parameters.Pack, true), eq(parameters.Sign, true)) }}:
              - template: .azure-pipelines/common-templates/esrp/codesign-nuget-migrate.yml@self
                parameters:
                  FolderPath: "$(Build.ArtifactStagingDirectory)"
                  Pattern: "Microsoft.Graph.Entra.*.nupkg"

              # - task: PublishBuildArtifacts@1
              #   displayName: Publish Module Artifacts
              #   inputs:
              #     PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              #     ArtifactName: "drop"
              #     publishLocation: "Container"
              - task: 1ES.PublishBuildArtifacts@1
                displayName: Publish Module Artifacts
                inputs:
                  PathtoPublish: $(Build.ArtifactStagingDirectory)
                  ArtifactName: drop

              # - task: NuGetCommand@2
              #   displayName: Publish NuGet to preview feed
              #   inputs:
              #     command: push
              #     packagesToPush: $(Build.ArtifactStagingDirectory)/**/Microsoft.Graph.Entra.*.nupkg
              #     publishVstsFeed: $(PROJECT_NAME)/$(PREVIEW_FEED_NAME)
              #     allowPackageConflicts: true

              - task: 1ES.PublishNuget@1
                displayName: Publish NuGet to preview feed
                inputs:
                  useDotNetTask: false
                  packagesToPush: $(Build.ArtifactStagingDirectory)/**/Microsoft.Graph.Entra.*.nupkg
                  packageParentPath: '$(Build.ArtifactStagingDirectory)'
                  publishVstsFeed: $(PROJECT_NAME)/$(PREVIEW_FEED_NAME)
                  nuGetFeedType: internal
                  allowPackageConflicts: true

          - template: .azure-pipelines/common-templates/security-post-checks.yml@self