# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# https://aka.ms/yaml

name: $(SourceBranchName)-PR-$(Date:yyyy-MM-dd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - main

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: windows-latest
stages:
- stage: Build
  displayName: 'Build Compatibility Adapter'
  jobs:
  - job: Build
    displayName: Microsoft Graph Compatibility Adapter Build and Artifact Generations
    steps:
      - template: ./generation-templates/generate_adapter.yml
        parameters:
          Sign: false
      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
        displayName: 'Component Detection'
        inputs:
          failOnAlert: true